server:
  port: 8085

spring:
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/edumon
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.chunjae
  mapper-locations: mappers/**/*.xml


# properties 방식
# server.port=8085
## spring boot jsp setting
#    spring.mvc.view.prefix=/WEB-INF/view
#    spring.mvc.view.suffix=.jsp
#
#  # spring jdbc setting
#  # key=value: no white-space between equals(=)
#    spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#    spring.datasource.url=jdbc.mariadb://localhost:3306/edumon
#    spring.datasource.username=root
#    spring.datasource.password=1234
#
#    mybatis.type-aliases-package=com.chunjae
#    mybatis.mapper-locations=mappers/**/*.xml