server:
  port: 8085

logging:
  level:
    org:
      springframework: info
    com:
      springdata: debug

spring:
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true # CRUD? ??? ? ? ??.
    show-sql: true # JPA? SQL? ???? ???
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springData
    username: root
    password: 1234
  servlet:
    multipart:
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB